### ISSUE TITLE
Layout da pesquisa de ramais

### ISSUE THREAD

**Issue by edersoncosta** [aleodoni/chamados#17]
Onde está escrito Controle de Chamados da Telefonia podemos colocar como:
Telefonia - Lista de Ramais
No rodapé, colocar info sobre o desenvolvimento:
Desenvolvido pela Seção de Telefonia @ 2016 (Se for conveniente a vc colocar nossos nomes e claro a linguagem de desenvolvimento).
Também colocar info para contato junto a Seção:
Contato
Telefonistas: disque 11 
Chefia: Ederson F. Costa Ramal 4897/4829  ou 70011 ederson.costa@cmc.pr.gov.br /

**Comment by aleodoni** [comment]
Acredito que a melhor opção seria : Software Livre. A Seção de Telefonia contribui para a comunidade.
O contato, etc... continua como vc sugeriu

**Comment by edersoncosta** [comment]
Pode ser cara, acredito que fica bom assim. Manda bala
