### ISSUE TITLE
Tela de abertura de Chamado para usuário

### ISSUE THREAD

**Issue by edersoncosta** [aleodoni/chamados#3]
Desenvolver uma tela que poderá ser acessada pela intranet na qual o usuário pode registrar um chamado para Telefonia.

**Comment by aleodoni** [comment]
Ok, Ederson, tendo em vista a tela de chamados, imagino que esta tela seria mais ou menos assim :

1) Data do chamado (do dia - sem opção de alteração)
2) Setor (acredito que a melhor opção seria já trazer o setor do usuário logado; não sei se é interessante ter opção de escolher outro(s) setor(es))
3) Ramal (também, se for o caso trazer apenas os ramais do setor selecionado em 2)
4) Descrição do problema

**Comment by aleodoni** [comment]
Criada a tela para abertura de chamados por terceiros. Ainda falta implementar no sistema as verificações de permissão. Para a tela de chamado de terceiros, não será necessário logar-se no sistema. Para as demais, sim.

## IMPORTANTE

No final do arquivo settings.py foram criadas 3 variáveis globais. Essas variáveis preenchem com os valores das chaves primárias os campos (Status, Urgência e Executor) tanto na tela de pesquisa quanto na tela de chamados de terceiros. 
Não esquecer de modificar esses valores quando for utilizar o sistema.
