### ISSUE TITLE
Implementação de Abertura de chamados por terceiros.

### ISSUE THREAD

**Issue by edersoncosta** [aleodoni/chamados#5]
Criação de tela para que o usuário abra o chamado para a telefonia e o mesmo envie mensagem para o administrador.

**Comment by aleodoni** [comment]
# Tela
- Data de abertura do chamado
- Departamento (combo)
- Solicitante
- Ramal atendimento (combo)
- Ramal contato (combo)
- Problema

**Comment by aleodoni** [comment]
# Funcionamento

Qualquer usuário terá acesso a essa tela (única tela do sistema sem necessidade de login) e poderá abrir um chamado de forma simples para o setor de telefonia.

Para isso, basta preencher os campos acima e clicar no botão abrir chamado.

Feito isso, essa solicitação aparecerá automaticamente na tela do administrador do sistema e ele entrará em contato com o solicitante e também atualizará o status e as informações do chamado.

O solicitante não tem acesso para acompanhamento do chamado, pelo menos por enquanto. Caso isso seja necessário posteriormente, deverá haver o cadastramento de solicitante no sistema para que o mesmo possa acessar a tela de consulta de chamados.

**Comment by aleodoni** [comment]
A princípio está funcionando de acordo com o especificado. vou fechar a issue; se for o caso, poderá ser reaberta.
