### ISSUE TITLE
Alterações na Tela de abertura pelo usuário

### ISSUE THREAD

**Issue by edersoncosta** [aleodoni/chamados#6]
Podemos já alterar lá no alto onde diz "Abertura de Chamados por Terceiros" para Abertura de Chamados; 
Tirar o Logout na barra de menu;
Em "Ramal Atendimento " para "ramal com defeito"
Acredito que para o usuário isso ficará mais claro.

**Comment by aleodoni** [comment]
feito. fechando issue
