### ISSUE TITLE
Inclusão de campo e-mail  na tela de abertura de chamados dos usuários

### ISSUE THREAD

**Issue by edersoncosta** [aleodoni/chamados#7]
Criar campo  "e-mail", no qual o usuário insere seu e-mail de contato e recebe um recibo no e-mail de que seu ticket foi atribuído ao analista e quando o mesmo é encerrado.

**Comment by aleodoni** [comment]
Implementado.

**Comment by aleodoni** [comment]
Especificar o corpo do email que será enviado ao usuário, quais campos do chamado, etc.

**Comment by aleodoni** [comment]
Sempre que o chamado for atualizado, enviar email para o usuário informando da alteração

**Comment by aleodoni** [comment]
Ederson, vc me precisa então passar uma conta do gmail para eu configurar a aplicação

**Comment by aleodoni** [comment]
Fechando issue.
