### ISSUE TITLE
Data de abertura do chamado

### ISSUE THREAD

**Issue by edersoncosta** [aleodoni/chamados#8]
No campo "abertura", trocar o nome para "data de abertura", onde a data será fixada a partir do dia corrente da abertura do chamado, permitindo somente que o mesmo só possa ser aberto para data do dia ou futura.

**Comment by aleodoni** [comment]
Acho melhor então deixar fixo para a data corrente; assim não terá margem a erros.

**Comment by aleodoni** [comment]
Confirme para mim se essa validação de data se aplica apenas à abertura de chamados por terceiros ou na tela de abertura de chamados também.

**Comment by edersoncosta** [comment]
Somente na abertura de chamados por terceiros. Na tela de registro de chamado que alimento por vezes registro o chamado depois de ocorrido, em um período oportuno futuro aplicamos pra essa tela tbm, mas por enquanto somente a chamados de terceiros

**Comment by aleodoni** [comment]
Implementado. Fechando issue
