### ISSUE TITLE
Combo "Problemas Comuns"

### ISSUE THREAD

**Issue by edersoncosta** [aleodoni/chamados#9]
Combo que será ligada a tabela de problemas comuns, assim, quando o usuário abrir o chamado poderá selecionar um problema que já é de conhecimento da Seção e selecionando isso, não terá obrigatoriedade de preencher o campo problema.

**Comment by aleodoni** [comment]
Beleza. Para isso criaremos uma tabela com o respectivo cadastro no admin do sistema.

**Comment by aleodoni** [comment]
Criando tabela problemas_comuns que irá conter campo descrição. Ederson, favor confirmar

**Comment by aleodoni** [comment]
Ederson,

Perguntas : 

1) Essa combo deve ficar em que posição na tela  de abertura de chamados ?
2) Deve ficar nas duas telas (abertura de chamados e abertura de chamados por terceiros) ?
3) É campo obrigatório ?
4) O campo problema que hoje é obrigatório continua obrigatório ou não ?

**Comment by edersoncosta** [comment]
1) Essa combo deve ficar em que posição na tela de abertura de chamados ?
Na tela de abertura de chamados pode ficar acima da combo problema em ambas as telas.
2) Deve ficar nas duas telas (abertura de chamados e abertura de chamados por terceiros) ?
Acredito que pode ficar nas duas telas.
3) É campo obrigatório ?
Sim, deve ser obrigatório.
4) O campo problema que hoje é obrigatório continua obrigatório ou não ?
Acredito que não precise ser obrigatório se a combo for preenchida. Mesmo pq sabemos que o usuário em muitos casos tem preguiça de preencher, fica mais como um campo a mais para descrever com detalhes. mesmo porque se vamos ter uma combo problema, campo problema pode ser chamado de detalhamento do problema, o que acha?

**Comment by aleodoni** [comment]
Beleza então. Fica a combo obrigatória e o campo detalhamento do problema não.

**Comment by aleodoni** [comment]
Implementado. Fechando issue
